plugins {
    id 'java'
}

group = 'com.hochul'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.4'
    implementation 'software.amazon.awssdk:dynamodb-enhanced:2.25.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
}

jar {
    archiveFileName = 'todo-app.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

build.dependsOn jar
